name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Check Git status
        id: git
        shell: bash
        run: |
          RESULT=$(git status)
          echo "::set-output name=status::$RESULT"
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        run: gradle clean publish reobfJar -Preckon.stage=final
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch latest tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          tag_name: ${{ steps.latesttag.outputs.tag }}
          generate_release_notes: true
      - name: Cleanup old packages
        uses: actions/delete-package-versions@v2
        with:
          package-name: 'de.richie93.gsinfo'
          min-versions-to-keep: 10
      - name: Cleanup old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 10
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
